# Assignment 8

### Embedding Models
Small: sentence-transformers/all-MiniLM-L6-v2
- Maximum Sequence Length: 256 Tokens

Medium: sentence-transformers/all-mpnet-base-v2
- Maximum Sequence Length: 384 Tokens

Large: BAAI/bge-large-en-v1.5
- Maximum Sequence Length: 512 Tokens


### Generation Model
Qwen/Qwen2.5-3B-Instruct

In [3]:
from sentence_transformers import SentenceTransformer
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import torch

In [4]:
model_names = [
    "sentence-transformers/all-MiniLM-L6-v2", # Small
    "sentence-transformers/all-mpnet-base-v2", # Medium
    "BAAI/bge-large-en-v1.5"                   # Large
]

In [5]:
small_model = SentenceTransformer(model_names[0])
medium_model = SentenceTransformer(model_names[1])
large_model = SentenceTransformer(model_names[2])

embedding_models = {
    "small": small_model,
    "medium": medium_model,
    "large": large_model
}

print("Loaded models:")
for name, model in embedding_models.items():
    print(f"{name}: {model}")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\urvic\anaconda3\envs\myenv-django\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\urvic\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\urvic\anaconda3\envs\myenv-django\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\urvic\.cache\huggingface\hub\models--BAAI--bge-large-en-v1.5. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/779 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

BertModel LOAD REPORT from: BAAI/bge-large-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

Loaded models:
small: SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)
medium: SentenceTransformer(
  (0): Transformer({'max_seq_length': 384, 'do_lower_case': False, 'architecture': 'MPNetModel'})
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)
large: SentenceTransformer(
  (0): Transformer({'max_seq_length': 512, 'do_lower_case': True, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 1024, 'pooling_mode_cls_token': True, 'pooling_mode_mean_tokens': False, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

Text Representation

In [6]:
df = pd.read_csv("uiuc_student_marketplace_knowledge_base.csv")
df.head()

,paragraph_id,listing_type,title,paragraph_text
0,1,Service,Calculus and Linear Algebra Tutoring,A UIUC junior in engineering offers personaliz...
1,2,Service,Python and Java Programming Tutoring,A UIUC computer science student provides one-o...
2,3,Service,Chemistry and Biology Exam Prep,A pre-med student offers tutoring for general ...
3,4,Service,Graduation Photography Sessions,A student photographer offers graduation photo...
4,5,Service,Event and Club Photography,A UIUC student photographer provides event cov...

In [7]:
df["word_count"] = df["paragraph_text"].apply(lambda x: len(str(x).split()))

In [8]:
paragraphs = df.to_dict(orient="records")

Chunking Strategies

In [9]:
# Fixed Length Chunking
def fixed_length_chunking(paragraphs, target_words=300, max_words=360):
    chunks = []
    current_chunk = []
    current_word_count = 0
    chunk_num = 1

    for para in paragraphs:
        para_text = para["paragraph_text"]
        para_words = para["word_count"]

        # If current chunk is empty, always start with this paragraph
        if not current_chunk:
            current_chunk.append(para)
            current_word_count += para_words
            continue

        # If adding this paragraph keeps us within the soft target/max, add it
        if current_word_count + para_words <= max_words:
            current_chunk.append(para)
            current_word_count += para_words
        else:
            # Save the current chunk
            chunk_text = " ".join([p["paragraph_text"] for p in current_chunk])

            chunks.append({
                "chunk_id": f"fixed_{chunk_num:03d}",
                "strategy": "fixed",
                "paragraph_ids": [p["paragraph_id"] for p in current_chunk],
                "text": chunk_text,
                "word_count": current_word_count
            })

            # Start a new chunk with the current paragraph
            chunk_num += 1
            current_chunk = [para]
            current_word_count = para_words

    # Save final chunk
    if current_chunk:
        chunk_text = " ".join([p["paragraph_text"] for p in current_chunk])
        chunks.append({
            "chunk_id": f"fixed_{chunk_num:03d}",
            "strategy": "fixed",
            "paragraph_ids": [p["paragraph_id"] for p in current_chunk],
            "text": chunk_text,
            "word_count": current_word_count
        })

    return chunks

In [10]:
fixed_chunks = fixed_length_chunking(paragraphs, target_words=300, max_words=360)

print("Number of fixed chunks:", len(fixed_chunks))
print()
print(fixed_chunks[0]["chunk_id"])
print(fixed_chunks[0]["paragraph_ids"])
print(fixed_chunks[0]["word_count"])
print(fixed_chunks[0]["text"])

Number of fixed chunks: 14

fixed_001
[1, 2, 3]
339
A UIUC junior in engineering offers personalized tutoring in calculus and linear algebra for students taking introductory and intermediate math courses. Sessions are designed around the student's syllabus, homework set, and exam schedule, with extra practice on topics such as derivatives, integration techniques, vector spaces, matrices, determinants, and eigenvalues. The tutor focuses on explaining why methods work instead of only showing formulas, so students can solve unfamiliar problems independently. Meetings can be held at Grainger, the Main Library, or over Zoom, and review packets can be created before midterms. This service is especially useful for students who want structured weekly support, last-minute exam preparation, or patient help working through difficult lecture material. A UIUC computer science student provides one-on-one programming tutoring for beginners learning Python or Java. The service helps students understand syntax, debugging, loops, functions, arrays, object-oriented programming, and common assignment patterns used in introductory CS courses. Sessions typically include a short concept review, guided coding practice, and time for debugging class projects or homework submissions. The tutor can also explain how to read compiler errors, write cleaner code, and prepare for coding quizzes and technical interviews. Meetings are available online or in campus study spaces, and students can book single sessions or recurring weekly help. This listing is ideal for anyone who feels stuck in class and wants practical explanations with step-by-step examples. A pre-med student offers tutoring for general chemistry, organic chemistry foundations, and introductory biology courses at UIUC. Sessions focus on lecture review, reaction patterns, problem solving, vocabulary retention, and test-taking strategies for science-heavy exams. Students can bring lecture slides, worksheets, and practice tests, and the tutor will help organize the material into manageable study goals. Support is available for understanding mechanisms, cellular processes, lab concepts, and multiple-choice reasoning. The tutor emphasizes consistency by creating weekly study plans that fit around classes and club commitments. Appointments can be scheduled before major exams or used throughout the semester. This service works well for students who want accountability, clearer explanations, and extra confidence before quizzes and midterms.

In [11]:
# Overlapping Paragraph Chunking

def overlapping_paragraph_chunking(paragraphs, window_size=2, stride=1):
    chunks = []
    chunk_num = 1

    for i in range(0, len(paragraphs) - window_size + 1, stride):
        window = paragraphs[i:i + window_size]
        chunk_text = " ".join(p["paragraph_text"] for p in window)

        chunks.append({
            "chunk_id": f"overlap_{chunk_num:03d}",
            "strategy": "overlap",
            "paragraph_ids": [p["paragraph_id"] for p in window],
            "text": chunk_text,
            "word_count": sum(p["word_count"] for p in window)
        })

        chunk_num += 1

    return chunks

In [12]:
overlap_chunks = overlapping_paragraph_chunking(paragraphs, window_size=2, stride=1)

print("Number of overlap chunks:", len(overlap_chunks))
print(overlap_chunks[0]["chunk_id"])
print(overlap_chunks[0]["paragraph_ids"])
print(overlap_chunks[0]["word_count"])
print(overlap_chunks[0]["text"][:500])

Number of overlap chunks: 39
overlap_001
[1, 2]
225
A UIUC junior in engineering offers personalized tutoring in calculus and linear algebra for students taking introductory and intermediate math courses. Sessions are designed around the student's syllabus, homework set, and exam schedule, with extra practice on topics such as derivatives, integration techniques, vector spaces, matrices, determinants, and eigenvalues. The tutor focuses on explaining why methods work instead of only showing formulas, so students can solve unfamiliar problems indep

In [13]:
# Hybrid / Strategy Chunking

def assign_semantic_category(row):
    title = row["title"].lower()
    listing_type = row["listing_type"].lower()

    if listing_type == "service":
        if any(word in title for word in ["tutor", "programming", "language", "music", "resume"]):
            return "education"
        elif any(word in title for word in ["photo", "video", "design", "website"]):
            return "creative"
        elif any(word in title for word in ["hair", "nail", "makeup"]):
            return "beauty"
        elif any(word in title for word in ["pet", "dog"]):
            return "pet_care"
        elif any(word in title for word in ["moving", "cleaning", "laundry", "bike", "tech"]):
            return "student_help"
        else:
            return "other_services"

    elif listing_type == "product":
        if any(word in title for word in ["laptop", "monitor", "camera", "printer", "headphones", "console"]):
            return "electronics"
        elif any(word in title for word in ["chair", "bed", "mattress", "sofa", "table", "lamp"]):
            return "furniture_home"
        elif any(word in title for word in ["backpack", "sneakers", "jacket"]):
            return "fashion"
        elif any(word in title for word in ["fridge", "microwave", "kitchen"]):
            return "appliances_kitchen"
        else:
            return "other_products"

    return "uncategorized"

In [14]:
df["semantic_category"] = df.apply(assign_semantic_category, axis=1)
paragraphs = df.to_dict(orient="records")

In [15]:
def hybrid_chunking(paragraphs, max_words=350):
    chunks = []
    chunk_num = 1

    grouped = {}
    for para in paragraphs:
        category = para["semantic_category"]
        grouped.setdefault(category, []).append(para)

    for category, items in grouped.items():
        current_chunk = []
        current_word_count = 0

        for para in items:
            para_words = para["word_count"]

            if not current_chunk:
                current_chunk.append(para)
                current_word_count += para_words
                continue

            if current_word_count + para_words <= max_words:
                current_chunk.append(para)
                current_word_count += para_words
            else:
                chunk_text = " ".join(p["paragraph_text"] for p in current_chunk)

                chunks.append({
                    "chunk_id": f"hybrid_{chunk_num:03d}",
                    "strategy": "hybrid",
                    "semantic_category": category,
                    "paragraph_ids": [p["paragraph_id"] for p in current_chunk],
                    "text": chunk_text,
                    "word_count": current_word_count
                })

                chunk_num += 1
                current_chunk = [para]
                current_word_count = para_words

        if current_chunk:
            chunk_text = " ".join(p["paragraph_text"] for p in current_chunk)

            chunks.append({
                "chunk_id": f"hybrid_{chunk_num:03d}",
                "strategy": "hybrid",
                "semantic_category": category,
                "paragraph_ids": [p["paragraph_id"] for p in current_chunk],
                "text": chunk_text,
                "word_count": current_word_count
            })

            chunk_num += 1

    return chunks

In [16]:
hybrid_chunks = hybrid_chunking(paragraphs, max_words=350)

print("Number of hybrid chunks:", len(hybrid_chunks))
print(hybrid_chunks[0]["chunk_id"])
print(hybrid_chunks[0]["semantic_category"])
print(hybrid_chunks[0]["paragraph_ids"])
print(hybrid_chunks[0]["word_count"])
print(hybrid_chunks[0]["text"][:500])

Number of hybrid chunks: 19
hybrid_001
education
[1, 2, 11]
341
A UIUC junior in engineering offers personalized tutoring in calculus and linear algebra for students taking introductory and intermediate math courses. Sessions are designed around the student's syllabus, homework set, and exam schedule, with extra practice on topics such as derivatives, integration techniques, vector spaces, matrices, determinants, and eigenvalues. The tutor focuses on explaining why methods work instead of only showing formulas, so students can solve unfamiliar problems indep

In [17]:
print("Fixed chunks:", len(fixed_chunks))
print("Overlap chunks:", len(overlap_chunks))
print("Hybrid chunks:", len(hybrid_chunks))

Fixed chunks: 14
Overlap chunks: 39
Hybrid chunks: 19

In [18]:
def preview_chunks(chunks, n=2):
    for chunk in chunks[:n]:
        print("=" * 80)
        print("Chunk ID:", chunk["chunk_id"])
        print("Paragraph IDs:", chunk["paragraph_ids"])
        if "semantic_category" in chunk:
            print("Category:", chunk["semantic_category"])
        print("Word Count:", chunk["word_count"])
        print(chunk["text"][:600], "...\n")

print("FIXED CHUNKS")
preview_chunks(fixed_chunks)

print("OVERLAP CHUNKS")
preview_chunks(overlap_chunks)

print("HYBRID CHUNKS")
preview_chunks(hybrid_chunks)

FIXED CHUNKS
================================================================================
Chunk ID: fixed_001
Paragraph IDs: [1, 2, 3]
Word Count: 339
A UIUC junior in engineering offers personalized tutoring in calculus and linear algebra for students taking introductory and intermediate math courses. Sessions are designed around the student's syllabus, homework set, and exam schedule, with extra practice on topics such as derivatives, integration techniques, vector spaces, matrices, determinants, and eigenvalues. The tutor focuses on explaining why methods work instead of only showing formulas, so students can solve unfamiliar problems independently. Meetings can be held at Grainger, the Main Library, or over Zoom, and review packets can b ...

================================================================================
Chunk ID: fixed_002
Paragraph IDs: [4, 5, 6]
Word Count: 349
A student photographer offers graduation photo sessions around popular UIUC landmarks including the Quad, Alma Mater, Foellinger Auditorium, and the Main Library steps. Each session includes pose guidance, candid shots, solo portraits, and small group photos with friends or family. Clients can bring multiple outfits, cap and gown accessories, champagne props, or cultural stoles to customize the shoot. Edited high-resolution images are delivered in an online gallery within seven days, with color correction and light retouching included. The photographer aims to capture both polished portraits a ...

OVERLAP CHUNKS
================================================================================
Chunk ID: overlap_001
Paragraph IDs: [1, 2]
Word Count: 225
A UIUC junior in engineering offers personalized tutoring in calculus and linear algebra for students taking introductory and intermediate math courses. Sessions are designed around the student's syllabus, homework set, and exam schedule, with extra practice on topics such as derivatives, integration techniques, vector spaces, matrices, determinants, and eigenvalues. The tutor focuses on explaining why methods work instead of only showing formulas, so students can solve unfamiliar problems independently. Meetings can be held at Grainger, the Main Library, or over Zoom, and review packets can b ...

================================================================================
Chunk ID: overlap_002
Paragraph IDs: [2, 3]
Word Count: 227
A UIUC computer science student provides one-on-one programming tutoring for beginners learning Python or Java. The service helps students understand syntax, debugging, loops, functions, arrays, object-oriented programming, and common assignment patterns used in introductory CS courses. Sessions typically include a short concept review, guided coding practice, and time for debugging class projects or homework submissions. The tutor can also explain how to read compiler errors, write cleaner code, and prepare for coding quizzes and technical interviews. Meetings are available online or in campu ...

HYBRID CHUNKS
================================================================================
Chunk ID: hybrid_001
Paragraph IDs: [1, 2, 11]
Category: education
Word Count: 341
A UIUC junior in engineering offers personalized tutoring in calculus and linear algebra for students taking introductory and intermediate math courses. Sessions are designed around the student's syllabus, homework set, and exam schedule, with extra practice on topics such as derivatives, integration techniques, vector spaces, matrices, determinants, and eigenvalues. The tutor focuses on explaining why methods work instead of only showing formulas, so students can solve unfamiliar problems independently. Meetings can be held at Grainger, the Main Library, or over Zoom, and review packets can b ...

================================================================================
Chunk ID: hybrid_002
Paragraph IDs: [20]
Category: education
Word Count: 113
A bilingual UIUC student offers language tutoring in Spanish and Mandarin for beginners and intermediate learners. Lessons can focus on conversation practice, pronunciation, grammar, vocabulary review, listening exercises, or class support depending on the student's goals. Sessions are adapted for people preparing for exams as well as those who simply want more confidence speaking in everyday situations. The tutor can create custom review sheets and short practice assignments between meetings to reinforce progress. In-person sessions can take place on campus, while online meetings are also ava ...

In [19]:
fixed_chunks_df = pd.DataFrame(fixed_chunks)
overlap_chunks_df = pd.DataFrame(overlap_chunks)
hybrid_chunks_df = pd.DataFrame(hybrid_chunks)

fixed_chunks_df.to_csv("fixed_chunks.csv", index=False)
overlap_chunks_df.to_csv("overlap_chunks.csv", index=False)
hybrid_chunks_df.to_csv("hybrid_chunks.csv", index=False)

Embedding Pipeline

In [20]:
chunk_sets = {
    "fixed": fixed_chunks,
    "overlap": overlap_chunks,
    "hybrid": hybrid_chunks
}

embedded_results = {}

for chunking_name, chunks in chunk_sets.items():
    embedded_results[chunking_name] = {}
    texts = [chunk["text"] for chunk in chunks]

    for model_size, model in embedding_models.items():
        embeddings = model.encode(
            texts,
            convert_to_numpy=True,
            normalize_embeddings=True,
            show_progress_bar=True
        )

        embedded_results[chunking_name][model_size] = {
            "chunks": chunks,
            "texts": texts,
            "embeddings": embeddings
        }

        print(f"Done: {chunking_name} + {model_size} -> {embeddings.shape}")

vector_stores = {}

for chunking_name, model_data in embedded_results.items():
    vector_stores[chunking_name] = {}

    for model_size, data in model_data.items():
        vector_stores[chunking_name][model_size] = {
            "chunks": data["chunks"],
            "texts": data["texts"],
            "embeddings": data["embeddings"]
        }

        print(
            f"Stored: {chunking_name} + {model_size} -> "
            f"{data['embeddings'].shape[0]} chunks, dim={data['embeddings'].shape[1]}"
        )

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Done: fixed + small -> (14, 384)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Done: fixed + medium -> (14, 768)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Done: fixed + large -> (14, 1024)

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

Done: overlap + small -> (39, 384)

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

Done: overlap + medium -> (39, 768)

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

Done: overlap + large -> (39, 1024)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Done: hybrid + small -> (19, 384)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Done: hybrid + medium -> (19, 768)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Done: hybrid + large -> (19, 1024)
Stored: fixed + small -> 14 chunks, dim=384
Stored: fixed + medium -> 14 chunks, dim=768
Stored: fixed + large -> 14 chunks, dim=1024
Stored: overlap + small -> 39 chunks, dim=384
Stored: overlap + medium -> 39 chunks, dim=768
Stored: overlap + large -> 39 chunks, dim=1024
Stored: hybrid + small -> 19 chunks, dim=384
Stored: hybrid + medium -> 19 chunks, dim=768
Stored: hybrid + large -> 19 chunks, dim=1024

Retrieval System

In [21]:
def retrieve_top_k(query, chunking_name="fixed", model_size="small", k=3):
    """
    query: user question string
    chunking_name: 'fixed', 'overlap', or 'hybrid'
    model_size: 'small', 'medium', or 'large'
    k: number of chunks to retrieve
    """
    # get the correct embedding model and stored embeddings
    model = embedding_models[model_size]
    store = vector_stores[chunking_name][model_size]

    # Query -> embedding
    query_embedding = model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    # similarity search
    similarities = cosine_similarity(query_embedding, store["embeddings"])[0]

    # top-k retrieval
    top_indices = np.argsort(similarities)[::-1][:k]

    results = []
    for rank, idx in enumerate(top_indices, start=1):
        chunk = store["chunks"][idx]

        result = {
            "rank": rank,
            "score": float(similarities[idx]),
            "chunk_id": chunk["chunk_id"],
            "paragraph_ids": chunk["paragraph_ids"],
            "text": chunk["text"]
        }

        if "semantic_category" in chunk:
            result["semantic_category"] = chunk["semantic_category"]

        results.append(result)

    return results

In [22]:
def print_retrieval_results(results, max_chars=700):
    for r in results:
        print("=" * 100)
        print(f"Rank: {r['rank']}")
        print(f"Score: {r['score']:.4f}")
        print(f"Chunk ID: {r['chunk_id']}")
        print(f"Paragraph IDs: {r['paragraph_ids']}")
        if "semantic_category" in r:
            print(f"Semantic Category: {r['semantic_category']}")
        print("Retrieved Text:")
        print(r["text"][:max_chars])
        print()

In [23]:
# test
test_queries = [
    "I need tutoring for calculus and linear algebra",
    "Who offers graduation photography on campus?",
    "I need someone to walk my dog during the week",
    "I am looking for a used laptop for coursework",
    "Do any listings offer hair styling or makeup for events?"
]

for q in test_queries:
    print("\n" + "#" * 120)
    print("QUERY:", q)
    results = retrieve_top_k(q, chunking_name="fixed", model_size="medium", k=3)
    print_retrieval_results(results, max_chars=500)

########################################################################################################################
QUERY: I need tutoring for calculus and linear algebra
====================================================================================================
Rank: 1
Score: 0.5315
Chunk ID: fixed_001
Paragraph IDs: [1, 2, 3]
Retrieved Text:
A UIUC junior in engineering offers personalized tutoring in calculus and linear algebra for students taking introductory and intermediate math courses. Sessions are designed around the student's syllabus, homework set, and exam schedule, with extra practice on topics such as derivatives, integration techniques, vector spaces, matrices, determinants, and eigenvalues. The tutor focuses on explaining why methods work instead of only showing formulas, so students can solve unfamiliar problems indep

====================================================================================================
Rank: 2
Score: 0.3974
Chunk ID: fixed_007
Paragraph IDs: [19, 20, 21]
Retrieved Text:
A UIUC student provides tech support for common laptop, tablet, and phone issues affecting school or personal use. Services include software installation, troubleshooting slow performance, printer setup, storage cleanup, Wi-Fi connection issues, and assistance with account configuration. Clients can also get help transferring files to a new device, setting up productivity tools, or diagnosing whether a problem looks fixable before paying for a repair shop. Appointments can be done in person for

====================================================================================================
Rank: 3
Score: 0.1843
Chunk ID: fixed_006
Paragraph IDs: [16, 17, 18]
Retrieved Text:
A student cleaner provides light cleaning services for dorm rooms, apartments, and shared student living spaces near UIUC. Services can include vacuuming, sweeping, wiping surfaces, bathroom cleaning, kitchen cleanup, trash removal, and general tidying before guests arrive or inspections take place. Clients can request one-time help or recurring visits depending on availability. Cleaning supplies can be provided by the cleaner for common tasks, though clients should mention any sensitivities, pe


########################################################################################################################
QUERY: Who offers graduation photography on campus?
====================================================================================================
Rank: 1
Score: 0.6432
Chunk ID: fixed_002
Paragraph IDs: [4, 5, 6]
Retrieved Text:
A student photographer offers graduation photo sessions around popular UIUC landmarks including the Quad, Alma Mater, Foellinger Auditorium, and the Main Library steps. Each session includes pose guidance, candid shots, solo portraits, and small group photos with friends or family. Clients can bring multiple outfits, cap and gown accessories, champagne props, or cultural stoles to customize the shoot. Edited high-resolution images are delivered in an online gallery within seven days, with color

====================================================================================================
Rank: 2
Score: 0.5209
Chunk ID: fixed_009
Paragraph IDs: [25, 26, 27]
Retrieved Text:
A used laptop in solid working condition is available for sale near UIUC and is suitable for coursework, online classes, browsing, document editing, and light programming. The device has a reliable battery for everyday use, a functioning webcam for meetings, and enough storage for academic files and common software. Cosmetic wear is minor and does not affect performance. The seller can share processor details, memory specifications, charger information, and current system condition so buyers kno

====================================================================================================
Rank: 3
Score: 0.4475
Chunk ID: fixed_003
Paragraph IDs: [7, 8, 9]
Retrieved Text:
A UIUC student nail artist offers gel manicures, press-on sizing, simple acrylic sets, and custom nail art for students preparing for events or simply wanting a new set for the week. Clients can choose from minimalist styles, chrome finishes, seasonal designs, or character-inspired ideas, and reference photos are welcome before booking. Appointments include shaping, cuticle care, color application, and finishing details, with extra time added for complex artwork. The artist uses sanitized tools


########################################################################################################################
QUERY: I need someone to walk my dog during the week
====================================================================================================
Rank: 1
Score: 0.3010
Chunk ID: fixed_004
Paragraph IDs: [10, 11, 12]
Retrieved Text:
A student dog walker provides short and extended walks for campus-area pet owners who need help during class, work, or travel days. Walks are tailored to the dog's age, size, and energy level, and the walker can reinforce simple commands such as sit, wait, and leash manners during the outing. Owners receive a quick update after each visit covering distance, behavior, water refill, and any concerns noticed along the route. Recurring weekly slots are available, which is helpful for graduate studen

====================================================================================================
Rank: 2
Score: 0.2517
Chunk ID: fixed_006
Paragraph IDs: [16, 17, 18]
Retrieved Text:
A student cleaner provides light cleaning services for dorm rooms, apartments, and shared student living spaces near UIUC. Services can include vacuuming, sweeping, wiping surfaces, bathroom cleaning, kitchen cleanup, trash removal, and general tidying before guests arrive or inspections take place. Clients can request one-time help or recurring visits depending on availability. Cleaning supplies can be provided by the cleaner for common tasks, though clients should mention any sensitivities, pe

====================================================================================================
Rank: 3
Score: 0.1953
Chunk ID: fixed_003
Paragraph IDs: [7, 8, 9]
Retrieved Text:
A UIUC student nail artist offers gel manicures, press-on sizing, simple acrylic sets, and custom nail art for students preparing for events or simply wanting a new set for the week. Clients can choose from minimalist styles, chrome finishes, seasonal designs, or character-inspired ideas, and reference photos are welcome before booking. Appointments include shaping, cuticle care, color application, and finishing details, with extra time added for complex artwork. The artist uses sanitized tools


########################################################################################################################
QUERY: I am looking for a used laptop for coursework
====================================================================================================
Rank: 1
Score: 0.4667
Chunk ID: fixed_009
Paragraph IDs: [25, 26, 27]
Retrieved Text:
A used laptop in solid working condition is available for sale near UIUC and is suitable for coursework, online classes, browsing, document editing, and light programming. The device has a reliable battery for everyday use, a functioning webcam for meetings, and enough storage for academic files and common software. Cosmetic wear is minor and does not affect performance. The seller can share processor details, memory specifications, charger information, and current system condition so buyers kno

====================================================================================================
Rank: 2
Score: 0.3728
Chunk ID: fixed_007
Paragraph IDs: [19, 20, 21]
Retrieved Text:
A UIUC student provides tech support for common laptop, tablet, and phone issues affecting school or personal use. Services include software installation, troubleshooting slow performance, printer setup, storage cleanup, Wi-Fi connection issues, and assistance with account configuration. Clients can also get help transferring files to a new device, setting up productivity tools, or diagnosing whether a problem looks fixable before paying for a repair shop. Appointments can be done in person for

====================================================================================================
Rank: 3
Score: 0.3720
Chunk ID: fixed_012
Paragraph IDs: [33, 34, 35]
Retrieved Text:
An adjustable desk lamp is available for sale and is well suited for students who study late, attend evening online classes, or want better lighting for reading and desk work. The lamp provides focused illumination without taking up too much surface space, making it a useful accessory for both dorm desks and apartment workstations. Its adjustable neck allows users to direct light where they need it most, whether they are writing notes, assembling small items, or working on art projects. The lamp


########################################################################################################################
QUERY: Do any listings offer hair styling or makeup for events?
====================================================================================================
Rank: 1
Score: 0.4222
Chunk ID: fixed_002
Paragraph IDs: [4, 5, 6]
Retrieved Text:
A student photographer offers graduation photo sessions around popular UIUC landmarks including the Quad, Alma Mater, Foellinger Auditorium, and the Main Library steps. Each session includes pose guidance, candid shots, solo portraits, and small group photos with friends or family. Clients can bring multiple outfits, cap and gown accessories, champagne props, or cultural stoles to customize the shoot. Edited high-resolution images are delivered in an online gallery within seven days, with color

====================================================================================================
Rank: 2
Score: 0.3951
Chunk ID: fixed_003
Paragraph IDs: [7, 8, 9]
Retrieved Text:
A UIUC student nail artist offers gel manicures, press-on sizing, simple acrylic sets, and custom nail art for students preparing for events or simply wanting a new set for the week. Clients can choose from minimalist styles, chrome finishes, seasonal designs, or character-inspired ideas, and reference photos are welcome before booking. Appointments include shaping, cuticle care, color application, and finishing details, with extra time added for complex artwork. The artist uses sanitized tools

====================================================================================================
Rank: 3
Score: 0.2350
Chunk ID: fixed_005
Paragraph IDs: [13, 14, 15]
Retrieved Text:
A UIUC student developer builds simple websites for student organizations, portfolios, personal brands, and small campus ventures. Services can include landing pages, multi-page sites, mobile-friendly layouts, contact forms, and basic backend integrations depending on project needs. The developer works with clients to understand the site's goals, visual style, required sections, and deadline, then delivers a clean and responsive final product. Technologies may include HTML, CSS, JavaScript, Reac

Generation Pipeline

In [24]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

generation_model_name = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(generation_model_name)

generation_model = AutoModelForCausalLM.from_pretrained(
    generation_model_name,
    torch_dtype=torch.float32
)

device = "cuda" if torch.cuda.is_available() else "cpu"
generation_model = generation_model.to(device)

print("Loaded generation model:", generation_model_name)
print("Using device:", device)

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

C:\Users\urvic\anaconda3\envs\myenv-django\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\urvic\.cache\huggingface\hub\models--Qwen--Qwen2.5-3B-Instruct. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Loaded generation model: Qwen/Qwen2.5-3B-Instruct
Using device: cpu

In [25]:
def build_rag_prompt(query, retrieved_results, max_chars_per_chunk=600):
    retrieved_context = "\n\n".join(
        [f"[Chunk {i+1}] {r['text'][:max_chars_per_chunk]}" for i, r in enumerate(retrieved_results)]
    )

    system_instruction = (
        "You are a helpful assistant for a UIUC student marketplace. "
        "Answer the user's question using only the retrieved context. "
        "Do not make up information. If the answer is not in the context, say so clearly."
    )

    prompt = f"""System Instruction:
{system_instruction}

Retrieved Context:
{retrieved_context}

User Query:
{query}

Answer:
"""
    return prompt

In [26]:
def generate_rag_answer(query, chunking_name="fixed", model_size="small", k=2, max_new_tokens=120):
    retrieved_results = retrieve_top_k(
        query=query,
        chunking_name=chunking_name,
        model_size=model_size,
        k=k
    )

    prompt = build_rag_prompt(query, retrieved_results)

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=512
    )
    inputs = {key: value.to(device) for key, value in inputs.items()}

    with torch.no_grad():
        outputs = generation_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    generated_text = tokenizer.decode(
        outputs[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    )

    return {
        "query": query,
        "chunking_name": chunking_name,
        "embedding_model_size": model_size,
        "retrieved_results": retrieved_results,
        "prompt": prompt,
        "final_answer": generated_text.strip()
    }

In [27]:
result = generate_rag_answer(
    query="Who offers graduation photography on campus?",
    chunking_name="fixed",
    model_size="small",
    k=1,
    max_new_tokens=30
)

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

### Part 2

In [28]:
import time
import pandas as pd

test_queries = [
    "I need tutoring for calculus and linear algebra",
    "Who offers graduation photography on campus?",
    "I need someone to walk my dog during the week",
    "I am looking for a used laptop for coursework",
    "Do any listings offer hair styling or makeup for events?"
]


configs = [
    {"model": "small", "chunking": "fixed"},
    {"model": "medium", "chunking": "fixed"},
    {"model": "large", "chunking": "fixed"},
    {"model": "small", "chunking": "overlap"},
    {"model": "medium", "chunking": "overlap"},
    {"model": "large", "chunking": "overlap"},
    {"model": "small", "chunking": "hybrid"},
    {"model": "medium", "chunking": "hybrid"},
    {"model": "large", "chunking": "hybrid"},
]

evaluation_data = []

print("Starting evaluation loop...")

for config in configs:
    m_size = config["model"]
    c_strategy = config["chunking"]

    print(f"Testing Config: Model={m_size}, Strategy={c_strategy}")

    for query in test_queries:
        start_time = time.time()

        retrieved_results = retrieve_top_k(query, chunking_name=c_strategy, model_size=m_size, k=2)

        result = generate_rag_answer(
            query=query,
            chunking_name=c_strategy,
            model_size=m_size,
            k=2,
            max_new_tokens=100
        )

        end_time = time.time()
        latency = end_time - start_time

        chunks_display = ""
        for r in retrieved_results:
            chunks_display += f"[Rank {r['rank']} (Score: {r['score']:.4f})]: {r['text'][:150]}...\\n\\n"

        evaluation_data.append({
            "Embedding Model": m_size,
            "Chunking Strategy": c_strategy,
            "Query": query,
            "Retrieved Context Quality": "",
            "Answer Quality": "",
            "Latency (s)": round(latency, 2),
            "Retrieved Chunks": chunks_display,
            "Generated Answer": result['final_answer'].split("Answer:")[-1].strip(),
            "Score": f"{retrieved_results[0]['score']:.4f}" if retrieved_results else "No match"
        })

evaluation_df = pd.DataFrame(evaluation_data)
evaluation_df.to_csv("evaluation_table.csv", index=False)

print("\nEvaluation Complete Table saved.")
evaluation_df.head()

Starting evaluation loop...
Testing Config: Model=small, Strategy=fixed

KeyboardInterrupt:

In [7]:
raw_ratings = """
High,High
High,High
High,High
High,Medium
Medium,High
High,High
High,High
High,High
High,High
Low,Medium
High,High
High,High
High,High
High,High
Low,Medium
High,High
High,High
High,Medium
High,Low
Medium,Low
High,High
High,Medium
High,High
High,Low
Medium,Low
High,High
High,High
High,High
High,Low
Medium,Low
High,High
High,Medium
High,High
High,Low
High,Low
High,High
High,Medium
High,High
High,Medium
High,Low
High,High
High,Medium
High,High
High,Medium
High,Low"""

retrieved_list = []
answer_list = []

for line in raw_ratings.strip().split('\n'):
    ret_val, ans_val = line.split(',')
    retrieved_list.append(ret_val.strip())
    answer_list.append(ans_val.strip())

evaluation_df['Retrieved Context Quality'] = retrieved_list
evaluation_df['Answer Quality'] = answer_list

evaluation_df.to_csv("evaluation_table_final.csv", index=False)

evaluation_df.head()

,Embedding Model,Chunking Strategy,Query,Retrieved Context Quality,Answer Quality,Latency (s),Retrieved Chunks,Generated Answer,Score
0,small,fixed,I need tutoring for calculus and linear algebra,High,High,11.14,[Rank 1 (Score: 0.5796)]: A UIUC junior in eng...,The UIUC junior in engineering offers personal...,0.5796
1,small,fixed,Who offers graduation photography on campus?,High,High,10.99,[Rank 1 (Score: 0.6489)]: A student photograph...,A student photographer offers graduation photo...,0.6489
2,small,fixed,I need someone to walk my dog during the week,High,High,10.76,[Rank 1 (Score: 0.5224)]: A student dog walker...,"Based on the retrieved context, it seems that ...",0.5224
3,small,fixed,I am looking for a used laptop for coursework,High,Medium,10.54,[Rank 1 (Score: 0.6347)]: A used laptop in sol...,"Based on the retrieved context, a used laptop ...",0.6347
4,small,fixed,Do any listings offer hair styling or makeup f...,Medium,High,13.00,[Rank 1 (Score: 0.3612)]: A UIUC student nail ...,"No, based on the provided listings, there are ...",0.3612